"""Runtime profile -> CiliumNetworkPolicy (cilium.io/v2) with FQDN egress.

Where standard NetworkPolicy cannot name hosts, Cilium can: toFQDNs with
matchName / matchPattern, backed by Cilium's DNS proxy (so DNS is allowed
through it with a dns rule). Selects pods labelled shield.votal.ai/profile.

L7 methods and paths are enforced only on plaintext ports: on TLS (443)
Cilium sees no HTTP without TLS interception, so they are listed in
``unsupported`` there. Pair with target k8s for the pod hardening.
"""

from __future__ import annotations

import yaml

from core.runtime_policy.compilers import Compiled, ExportContext
from core.runtime_policy.compilers.k8s import HASH_ANNOTATION, LABEL, dns_name, label_value

TARGET = "cilium"
TLS_PORTS = {443, 8443}


def _fqdn(host: str) -> dict:
    return {"matchPattern": host} if "*" in host else {"matchName": host}


def _path_regex(glob: str) -> str:
    out, i = "", 0
    while i < len(glob):
        if glob.startswith("**", i):
            out += ".*"
            i += 2
        elif glob[i] == "*":
            out += "[^/]*"
            i += 1
        else:
            out += "\\" + glob[i] if glob[i] in ".+?()[]{}^$|\\" else glob[i]
            i += 1
    return out


def compile_profile(profile: dict, ctx: ExportContext) -> Compiled:
    unsupported: list[str] = []
    notes: list[str] = []
    opts = ctx.options or {}
    name = dns_name(ctx.profile_name)
    lbl = label_value(ctx.profile_name, ctx.profile_hash)
    meta = {"name": name, "labels": {"app.kubernetes.io/managed-by": "votal-shield", LABEL: lbl},
            "annotations": {HASH_ANNOTATION: ctx.profile_hash}}
    if opts.get("namespace"):
        meta["namespace"] = str(opts["namespace"])

    egress = [{
        "toEndpoints": [{"matchLabels": {"k8s:io.kubernetes.pod.namespace": "kube-system",
                                         "k8s:k8s-app": "kube-dns"}}],
        "toPorts": [{"ports": [{"port": "53", "protocol": "ANY"}],
                     "rules": {"dns": [{"matchPattern": "*"}]}}],
    }]
    entries = [{"host": ctx.shield_host, "port": ctx.shield_port, "methods": ["*"],
                "paths": ["/**"]}] + profile["network"]["allow"]
    for a in entries:
        rule = {"toFQDNs": [_fqdn(a["host"])],
                "toPorts": [{"ports": [{"port": str(a["port"]), "protocol": "TCP"}]}]}
        restricted = a["methods"] != ["*"] or a["paths"] != ["/**"]
        if restricted and a["port"] not in TLS_PORTS:
            rule["toPorts"][0]["rules"] = {"http": [
                {**({"method": m} if m != "*" else {}), "path": _path_regex(p)}
                for m in a["methods"] for p in a["paths"]]}
        elif restricted:
            unsupported.append(f"network.allow {a['host']}:{a['port']} methods/paths: TLS; "
                               f"Cilium sees no HTTP without TLS interception. Enforced by "
                               f"OpenShell or Shield's tool checks")
        egress.append(rule)

    fs, proc = profile["filesystem"], profile["process"]
    if fs["deny"] or fs["read_only"] or fs["read_write"]:
        unsupported.append("filesystem rules: not part of a network policy; export target k8s "
                           "for the pod hardening")
    if proc["deny_commands"] or proc["allow_binaries"]:
        unsupported.append("process rules: not part of a network policy. Enforced by Shield's "
                           "tool checks (and OpenShell where it runs)")
    if profile["resources"]:
        unsupported.append("resources: not part of a network policy; export target k8s")

    doc = {"apiVersion": "cilium.io/v2", "kind": "CiliumNetworkPolicy", "metadata": meta,
           "spec": {"endpointSelector": {"matchLabels": {LABEL: lbl}}, "egress": egress}}
    header = (f"# CiliumNetworkPolicy generated by Votal Shield.\n"
              f"# Runtime profile: {ctx.profile_name}  ({ctx.profile_hash})\n"
              f"# Selects pods labelled {LABEL}={lbl}. Everything not listed is denied.\n")
    for u in unsupported:
        header += f"# NOT ENFORCED HERE: {u}\n"
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100)
    return Compiled(target=TARGET, artifact=header + body, content_type="application/yaml",
                    filename=f"{ctx.profile_name}.cilium.yaml", unsupported=unsupported,
                    notes=notes)
