"""Runtime profile -> Squid ACL fragment for the SWG (deploy/swg/squid.conf).

Scopes the profile to the agents' source addresses (option ``source_cidrs``,
required: an ACL without it would apply to every client of the proxy) and
allows only the profile's hosts and ports; everything else from those
sources is denied. Paste it ABOVE the existing http_access rules.

Squid sees the host of a CONNECT tunnel but not the HTTP method or path inside
TLS unless the host is bumped (the SWG bumps only AI hosts), so methods and
paths on TLS hosts are listed as unsupported.
"""

from __future__ import annotations

import re

from core.runtime_policy.compilers import Compiled, ExportContext

TARGET = "squid"


class SquidOptionError(ValueError):
    pass


def _acl(name: str) -> str:
    return "shield_" + re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")[:40]


def _dstdomain(host: str) -> str:
    # Squid: a leading dot matches the domain and every subdomain.
    return "." + host[2:] if host.startswith("*.") else host


def compile_profile(profile: dict, ctx: ExportContext) -> Compiled:
    opts = ctx.options or {}
    sources = opts.get("source_cidrs") or []
    if not sources:
        raise SquidOptionError("target squid needs source_cidr (the agents' addresses): an "
                               "ACL without it would apply to every client of the proxy")
    unsupported: list[str] = []
    notes: list[str] = []
    a = _acl(ctx.profile_name)
    entries = [{"host": ctx.shield_host, "port": ctx.shield_port, "methods": ["*"],
                "paths": ["/**"]}] + profile["network"]["allow"]
    domains = sorted({_dstdomain(e["host"]) for e in entries})
    ports = sorted({e["port"] for e in entries})
    for e in profile["network"]["allow"]:
        if e["methods"] != ["*"] or e["paths"] != ["/**"]:
            unsupported.append(f"network.allow {e['host']} methods/paths: inside TLS Squid sees "
                               f"only the host. Enforced by OpenShell or Shield's tool checks")
    for section in ("filesystem", "process"):
        unsupported.append(f"{section} rules: not part of a proxy policy")
    lines = [
        f"# Squid ACLs generated by Votal Shield for runtime profile {ctx.profile_name}",
        f"# ({ctx.profile_hash}). Paste ABOVE your existing http_access rules.",
        *[f"# NOT ENFORCED HERE: {u}" for u in unsupported],
        f"acl {a}_src src {' '.join(sources)}",
        f"acl {a}_dst dstdomain {' '.join(domains)}",
        f"acl {a}_ports port {' '.join(map(str, ports))}",
        f"http_access allow {a}_src {a}_dst {a}_ports",
        f"http_access deny {a}_src",
        "",
    ]
    notes.append(f"clients in {', '.join(sources)} may reach only {len(domains)} host(s)")
    return Compiled(target=TARGET, artifact="\n".join(lines), content_type="text/plain",
                    filename=f"{ctx.profile_name}.squid.conf", unsupported=unsupported,
                    notes=notes)
