"""The PAC file MDM points the laptop's proxy settings at (spec §3.1): AI hosts
to the local proxy, everything else DIRECT. Served by the loopback API at
/proxy.pac, from the current policy, so a bundle that adds a host changes the
PAC with no reinstall.

Host matching is the ICAP adapter's (icap/pac.py): each entry matches itself
and its subdomains, never a suffix collision.
"""

from __future__ import annotations

from icap.pac import _match_expr


def render(ai_hosts, proxy_port: int, *, fail_open: bool) -> str:
    """fail_open (fail_mode allow): if the agent's proxy is down, AI traffic goes
    DIRECT, uninspected. Otherwise AI hosts are unreachable until it is back."""
    fallback = "; DIRECT" if fail_open else ""
    note = ("fail_mode allow: if the agent is down, AI traffic continues uninspected."
            if fail_open else
            "fail_mode block: if the agent is down, AI hosts are unreachable.")
    return f"""// Generated by the Votal device agent. Do not edit by hand.
// {note}
function FindProxyForURL(url, host) {{
  host = host.toLowerCase();
  if (
{_match_expr(tuple(sorted(ai_hosts)))}
  ) {{
    return "PROXY 127.0.0.1:{int(proxy_port)}{fallback}";
  }}
  return "DIRECT";
}}
"""
