#!/usr/bin/env bash
# Mode A on GCP: Squid (TLS interception) + shield-icap, inside the customer's
# own VPC, screening prompts from GCP-resident workloads.
#
#   ./deploy-mode-a.sh <project> <region> <network> <client-cidr>
#   ./deploy-mode-a.sh --emit-startup        print the boot script and exit
#
# Spec: docs/spec-swg-gcp-mode-a.md. Operator guide: docs/swg-deployment.md.
#
# This is NOT deploy.sh. That script is Mode B: the adapter alone, for a site
# that already runs Zscaler, Netskope or similar and does its own decryption.
# Run `docker run --rm shield-icap preflight` if you are unsure which you want.
# Installing a second interception point where one already exists buys nothing
# and costs two forged chains and two bypass lists.
#
# Why Squid is here when deploy.sh deliberately excludes it: the objections to
# a cloud-hosted Squid are that a proxy on a public port is an open relay, and
# that the interception CA's private key belongs where the users are. Both hold
# for a laptop fleet dialling in over the internet. Neither holds here, because
# the clients ARE GCP workloads in this VPC: there is no public port (no
# external IP, internal passthrough LB, firewall scoped to the client range),
# and the VPC is the trust boundary the key already belongs in.
#
# Shape:
#
#   GCE / GKE client            swg-proxy MIG (no external IP)
#   HTTPS_PROXY ----- ILB:3128 -> squid :3128 --.
#   + CA trusted                                 | docker bridge, never
#                                                v published to the host
#                                               shield-icap :1344
#                                                 |
#                              Cloud NAT <--------'
#                                 |
#                                 v
#                   api.openai.com, api.anthropic.com, ...
#                   api.guardrails.votal.ai  (policy bundle + telemetry)
#
# Port 1344 never leaves the instance. In Mode B it needs a load balancer and a
# firewall because it answers "is this blocked?" and so is an oracle for the
# tenant's DLP patterns; here nothing outside the VM can open it at all.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SQUID_CONF="${REPO_ROOT}/deploy/swg/squid.conf"

# Read, never written by this script. The CA is generated by the operator and
# uploaded; see step 2 below and the deployment guide.
CA_SECRET="swg-ca-pem"
KEY_SECRET="shield-api-key"

# ── the boot script ──────────────────────────────────────────────────────────
# squid.conf is READ FROM THE REPO, not reproduced here. tests/test_icap_deploy.py
# already asserts that file's bypass list matches DEFAULT_BYPASS_HOSTS, that its
# AI host list matches DEFAULT_AI_HOSTS, and that splice is evaluated before
# bump. A second copy inlined in this script would sit outside those assertions,
# and a bypass list that drifts is a privacy incident rather than a bug.
emit_startup() {
  local icap_image="$1" squid_image="$2" proxy_ip="$3"

  cat <<'HEAD'
#!/bin/bash
# Generated by deploy/swg/gcp/deploy-mode-a.sh. Do not edit on the instance:
# the MIG replaces instances and the edit goes with them.
set -euo pipefail
exec 1> >(logger -t shield-swg) 2>&1

# Debian rather than Container-Optimized OS, deliberately. COS ships no gcloud,
# so fetching a secret there means hand-rolling a metadata-token call against
# the Secret Manager REST API and parsing JSON without jq. Debian's GCE image
# has gcloud preinstalled, and it can be debugged over IAP SSH with a package
# manager present. The cost is installing docker at boot, so an instance is not
# healthy until NAT egress works.
if ! command -v docker >/dev/null 2>&1; then
  apt-get update -qq
  apt-get install -y -qq docker.io
fi
systemctl enable --now docker

# Secrets onto tmpfs: absent from the boot disk, and so absent from any
# snapshot or image built off this instance.
mkdir -p /run/shield
mountpoint -q /run/shield || mount -t tmpfs -o size=1m,mode=0700 tmpfs /run/shield
HEAD

  cat <<EOF
gcloud secrets versions access latest --secret=${CA_SECRET}  > /run/shield/ca.pem
gcloud secrets versions access latest --secret=${KEY_SECRET} > /run/shield/api_key
EOF

  cat <<'MID'
chmod 600 /run/shield/ca.pem /run/shield/api_key
# The adapter runs as uid 65532 (non-root, per Dockerfile.icap) so a root-owned
# 0600 key is unreadable to it: it would start, load no policy, and block
# nothing while looking healthy. Squid keeps ca.pem root-only because its
# container does run as root and reads the CA before dropping to `proxy`.
chown 65532 /run/shield/api_key

mkdir -p /etc/shield
cat > /etc/shield/squid.conf <<'SQUIDCONF'
MID

  cat "$SQUID_CONF"

  cat <<'MID2'
SQUIDCONF

docker network inspect swg >/dev/null 2>&1 || docker network create swg
MID2

  # The adapter. 8081 is published for the load balancer's health check; 1344 is
  # NOT, so ICAP is reachable only over the docker bridge, by the Squid beside
  # it. squid.conf resolves it as icap://shield-icap:1344/screen, by container
  # name, so this container must keep this name.
  cat <<EOF

docker rm -f shield-icap >/dev/null 2>&1 || true
docker run -d --restart=always --name shield-icap --network swg \\
  -p 8081:8081 \\
  --read-only --user 65532 \\
  -v /run/shield/api_key:/run/secrets/api_key:ro \\
  -e SHIELD_API_KEY_FILE=/run/secrets/api_key \\
  -e SHIELD_ICAP_MODE=monitor \\
  -e SHIELD_ICAP_ALLOWED_CLIENTS=172.16.0.0/12 \\
  -e SHIELD_ICAP_PAC_PROXY=${proxy_ip}:3128 \\
  ${icap_image}

# Squid. The CA is bind-mounted read-only from tmpfs and never enters a layer.
docker rm -f squid >/dev/null 2>&1 || true
docker run -d --restart=always --name squid --network swg \\
  -p 3128:3128 \\
  -v /etc/shield/squid.conf:/etc/squid/squid.conf:ro \\
  -v /run/shield/ca.pem:/etc/squid/ssl/ca.pem:ro \\
  -v squid-ssldb:/var/spool/squid \\
  ${squid_image}
EOF
}

# Preview exactly what an instance will run, with no project and no gcloud.
if [ "${1:-}" = "--emit-startup" ]; then
  emit_startup "REGION-docker.pkg.dev/PROJECT/shield/shield-icap:latest" \
               "REGION-docker.pkg.dev/PROJECT/shield/shield-squid:latest" \
               "10.0.0.2"
  exit 0
fi

# ── deploy ───────────────────────────────────────────────────────────────────
PROJECT="${1:?usage: deploy-mode-a.sh <project> <region> <network> <client-cidr>}"
REGION="${2:?}"
NETWORK="${3:?}"
CLIENT_CIDR="${4:?}"            # the range your workloads run in
ZONE="${REGION}-a"

REGISTRY="${REGION}-docker.pkg.dev/${PROJECT}/shield"
ICAP_IMAGE="${REGISTRY}/shield-icap:latest"
SQUID_IMAGE="${REGISTRY}/shield-squid:latest"

gcloud config set project "$PROJECT" >/dev/null

echo "==> 1/9 APIs"
gcloud services enable compute.googleapis.com artifactregistry.googleapis.com \
  secretmanager.googleapis.com cloudbuild.googleapis.com iap.googleapis.com \
  >/dev/null

echo "==> 2/9 secrets"
# Neither secret is ever an environment variable on the template or a value in
# instance metadata: both of those are readable by anyone holding
# compute.instances.get, and one of them is a CA private key. They are fetched
# at boot, onto tmpfs, by a service account whose only grant is accessing them.
for s in "$CA_SECRET" "$KEY_SECRET"; do
  gcloud secrets describe "$s" >/dev/null 2>&1 || \
    gcloud secrets create "$s" --replication-policy=automatic >/dev/null
done

missing=0
for s in "$CA_SECRET" "$KEY_SECRET"; do
  if ! gcloud secrets versions describe latest --secret="$s" >/dev/null 2>&1; then
    echo "  MISSING: $s has no version" >&2
    missing=1
  fi
done
if [ "$missing" = 1 ]; then
  cat >&2 <<'NEEDSECRETS'

  Add them before deploying. Instances that boot without these crash-loop:
  Squid refuses to start without a CA (which is the correct failure -- a proxy
  that started without one could not bump anything and would pass everything).

  The CA is yours. This script will not generate one, so the private key is
  never produced inside automation or baked into an image:

    openssl req -new -newkey rsa:4096 -sha256 -days 1825 -nodes -x509 \
      -extensions v3_ca -keyout ca.pem -out ca.pem \
      -subj "/CN=Example Corp Internal Inspection"

    gcloud secrets versions add swg-ca-pem --data-file=ca.pem
    printf %s '<tenant key>' | gcloud secrets versions add shield-api-key --data-file=-

NEEDSECRETS
  exit 1
fi

echo "==> 3/9 images"
gcloud artifacts repositories describe shield --location="$REGION" >/dev/null 2>&1 || \
  gcloud artifacts repositories create shield --repository-format=docker --location="$REGION"

# Squid is BUILT, never pulled. The common images (ubuntu/squid included) are
# compiled --with-gnutls and ship no security_file_certgen, so ssl_bump does
# not exist and Squid refuses this config at startup. Debian's squid-openssl
# package is what Dockerfile.squid installs.
gcloud builds submit --config="${REPO_ROOT}/deploy/swg/gcp/cloudbuild.yaml" \
  --substitutions="_IMAGE=${ICAP_IMAGE},_DOCKERFILE=Dockerfile.icap" "$REPO_ROOT"
gcloud builds submit --config="${REPO_ROOT}/deploy/swg/gcp/cloudbuild.yaml" \
  --substitutions="_IMAGE=${SQUID_IMAGE},_DOCKERFILE=deploy/swg/Dockerfile.squid" "$REPO_ROOT"

echo "==> 4/9 service account"
SA="swg-proxy@${PROJECT}.iam.gserviceaccount.com"
gcloud iam service-accounts describe "$SA" >/dev/null 2>&1 || \
  gcloud iam service-accounts create swg-proxy --display-name="Shield SWG proxy"
for s in "$CA_SECRET" "$KEY_SECRET"; do
  gcloud secrets add-iam-policy-binding "$s" \
    --member="serviceAccount:${SA}" --role=roles/secretmanager.secretAccessor >/dev/null
done

echo "==> 5/9 subnet and reserved address"
SUBNET="$(gcloud compute networks subnets list --network="$NETWORK" \
  --filter="region:($REGION)" --format='value(name)' --limit=1)"
if [ -z "$SUBNET" ]; then
  echo "  no subnet for network '$NETWORK' in $REGION" >&2
  exit 1
fi
echo "  subnet: $SUBNET"

# Reserved up front so the proxy address is known before the instance template
# is built, and so it survives the load balancer being recreated. Clients point
# HTTPS_PROXY at this for the life of the deployment.
gcloud compute addresses describe swg-proxy-ip --region="$REGION" >/dev/null 2>&1 || \
  gcloud compute addresses create swg-proxy-ip --region="$REGION" --subnet="$SUBNET"
PROXY_IP="$(gcloud compute addresses describe swg-proxy-ip --region="$REGION" \
  --format='value(address)')"
echo "  proxy address: $PROXY_IP"

echo "==> 6/9 Cloud NAT"
# The instances have no external address, so this is their only way to reach
# the AI providers and api.guardrails.votal.ai.
gcloud compute routers describe swg-router --region="$REGION" >/dev/null 2>&1 || \
  gcloud compute routers create swg-router --network="$NETWORK" --region="$REGION" >/dev/null
gcloud compute routers nats describe swg-nat --router=swg-router --region="$REGION" >/dev/null 2>&1 || \
  gcloud compute routers nats create swg-nat --router=swg-router --region="$REGION" \
    --auto-allocate-nat-external-ips --nat-all-subnet-ip-ranges >/dev/null

echo "==> 7/9 startup script"
STARTUP="$(mktemp)"
trap 'rm -f "$STARTUP"' EXIT
emit_startup "$ICAP_IMAGE" "$SQUID_IMAGE" "$PROXY_IP" > "$STARTUP"

echo "==> 8/9 instance template and managed instance group"
# 2 vCPU: rule evaluation is CPU bound on bodies under 1 MiB and Squid's TLS
# work sits on top of it. Measure before changing.
gcloud compute instance-templates create swg-proxy-tpl \
  --machine-type=e2-standard-2 \
  --image-family=debian-12 --image-project=debian-cloud \
  --network="$NETWORK" --subnet="$SUBNET" --no-address \
  --service-account="$SA" --scopes=cloud-platform \
  --metadata-from-file=startup-script="$STARTUP" \
  --tags=swg-proxy 2>/dev/null || echo "  template exists, skipping"

# Two minimum. squid.conf ships bypass=off, so if the adapter is unreachable
# Squid blocks rather than forwarding uninspected: proxy availability is AI
# availability for every client behind it.
gcloud compute instance-groups managed create swg-proxy-mig \
  --template=swg-proxy-tpl --size=2 --zone="$ZONE" 2>/dev/null || echo "  MIG exists, skipping"
gcloud compute health-checks create tcp swg-proxy-hc --port=8081 2>/dev/null || true

echo "==> 9/9 internal load balancer and firewall"
# Passthrough, not an application load balancer: an ALB parses HTTP and this is
# a CONNECT-tunnelling proxy stream. Internal, because the proxy has no
# business being reachable from outside the VPC.
gcloud compute backend-services create swg-proxy-be \
  --load-balancing-scheme=INTERNAL --protocol=TCP \
  --region="$REGION" --health-checks=swg-proxy-hc 2>/dev/null || echo "  backend exists"
gcloud compute backend-services add-backend swg-proxy-be \
  --region="$REGION" --instance-group=swg-proxy-mig --instance-group-zone="$ZONE" \
  2>/dev/null || true
gcloud compute forwarding-rules create swg-proxy-fr \
  --load-balancing-scheme=INTERNAL --network="$NETWORK" --subnet="$SUBNET" \
  --address=swg-proxy-ip --region="$REGION" --ports=3128 \
  --backend-service=swg-proxy-be 2>/dev/null || echo "  forwarding rule exists"

# Only the client range may use the proxy.
gcloud compute firewall-rules create allow-swg-proxy \
  --network="$NETWORK" --allow=tcp:3128 \
  --source-ranges="$CLIENT_CIDR" --target-tags=swg-proxy 2>/dev/null || echo "  fw exists"
# Health checks come from Google's own probe ranges and nowhere else. 8081 also
# serves /healthz, which reports the rule count, so it is not opened to clients.
gcloud compute firewall-rules create allow-swg-proxy-hc \
  --network="$NETWORK" --allow=tcp:8081 \
  --source-ranges=35.191.0.0/16,130.211.0.0/22 --target-tags=swg-proxy \
  2>/dev/null || echo "  fw exists"
# Operator access without an external IP.
gcloud compute firewall-rules create allow-swg-proxy-iap-ssh \
  --network="$NETWORK" --allow=tcp:22 \
  --source-ranges=35.235.240.0/20 --target-tags=swg-proxy 2>/dev/null || echo "  fw exists"

# No rule opens 1344. That is not an omission: ICAP stays on the docker bridge.

cat <<SUMMARY

Deployed in monitor mode. Nothing is blocked yet and everything is reported,
which is the right day one. Flip to enforce by editing SHIELD_ICAP_MODE in the
startup script and rolling the MIG, after reviewing what would have blocked.

Point workloads at it:

  export HTTPS_PROXY=http://${PROXY_IP}:3128

Trust the CA on each client, and set the bundle variables too. Python and Node
ship their own trust stores and ignore update-ca-certificates, and forgetting
this is the single most common cause of "everything broke after the proxy":

  gcloud secrets versions access latest --secret=${CA_SECRET} \\
    | sudo tee /usr/local/share/ca-certificates/shield-ca.crt >/dev/null
  sudo update-ca-certificates
  export REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/shield-ca.crt
  export SSL_CERT_FILE=/usr/local/share/ca-certificates/shield-ca.crt
  export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/shield-ca.crt

Check policy actually loaded, over IAP:

  gcloud compute ssh <an-instance> --zone=${ZONE} --tunnel-through-iap \\
    --command 'curl -s localhost:8081/healthz'

'rules: 0' means no policy loaded and nothing will ever block, whatever the
mode says. Check that before trusting a quiet console.

A workload that ignores HTTPS_PROXY still reaches the provider directly and is
never screened. Until you deny egress on 443 to everything except this proxy,
this is a control against accidental leakage, not against a determined one.
SUMMARY
