"""Regenerate votal_device_agent/hook_scripts.py from the canonical Claude Code
hook scripts in core/runtime_policy/hook_scripts/.

The installers bundle the agent with PyInstaller --collect-submodules, which
takes modules but not data files, so the scripts ship as string constants.
tests/test_device_agent_hooks.py fails when this copy drifts.

    python packages/votal-device-agent/packaging/sync_hook_scripts.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "core" / "runtime_policy" / "hook_scripts"
OUT = ROOT / "packages" / "votal-device-agent" / "votal_device_agent" / "hook_scripts.py"


def render() -> str:
    sh = (SRC / "claude_code_hook.sh").read_text(encoding="utf-8")
    ps1 = (SRC / "claude_code_hook.ps1").read_text(encoding="utf-8")
    return ('"""The Claude Code hook scripts the agent installs (docs/specs/'
            'claude-code-fleet-rollout.md).\n\nGenerated by packaging/sync_hook_scripts.py '
            'from core/runtime_policy/hook_scripts/;\ndo not edit here.\n"""\n\n'
            f"CLAUDE_CODE_HOOK_SH = {sh!r}\n\nCLAUDE_CODE_HOOK_PS1 = {ps1!r}\n")


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT}")
