"""Emit a deployable Python MCP server from generated ToolSpecs.

The output depends only on `mcp` + `httpx` (not on Shield's codebase), so it runs
standalone. Shield enforcement is baked in but optional at runtime: set
SHIELD_URL and the server calls /v1/shield/tool/check before every tool call and
fails open if Shield is unreachable.
"""

from __future__ import annotations

import json
from typing import Iterable

from core.openapi.tool_mapper import ToolSpec


def _meta(tools: Iterable[ToolSpec]) -> list[dict]:
    return [{
        "name": t.name,
        "description": t.description,
        "inputSchema": t.input_schema,
        "method": t.method,
        "path": t.path,
        "param_locations": t.param_locations,
        "has_body": t.has_body,
        "risk": t.risk,
    } for t in tools]


_TEMPLATE = '''"""MCP server for @@TITLE@@ — generated by Votal Shield.

Run:
    pip install mcp httpx
    API_BASE_URL=@@BASE_URL@@ python server.py

Optional Shield enforcement (RBAC + kill switch) before each tool call:
    export SHIELD_URL=https://your-shield
    export SHIELD_API_KEY=...        SHIELD_AGENT_KEY=@@AGENT_KEY@@
    export SHIELD_USER_ROLE=...
"""

import os
import json
import httpx

from mcp.server import Server
from mcp.server.stdio import run_server
from mcp.types import Tool, TextContent

BASE_URL = os.environ.get("API_BASE_URL", "@@BASE_URL@@")
SHIELD_URL = os.environ.get("SHIELD_URL", "")
SHIELD_API_KEY = os.environ.get("SHIELD_API_KEY", "")
AGENT_KEY = os.environ.get("SHIELD_AGENT_KEY", "@@AGENT_KEY@@")
USER_ROLE = os.environ.get("SHIELD_USER_ROLE", "")

_TOOLS = json.loads(@@TOOLS_REPR@@)
_BY_NAME = {t["name"]: t for t in _TOOLS}

server = Server("@@SERVER_NAME@@")
_http = httpx.AsyncClient(timeout=30)


@server.list_tools()
async def list_tools():
    return [
        Tool(name=t["name"], description=t["description"], inputSchema=t["inputSchema"])
        for t in _TOOLS
    ]


async def _shield_allows(name, args):
    """Returns (allowed, reason). Fails open if Shield is unreachable."""
    if not SHIELD_URL:
        return True, ""
    try:
        r = await _http.post(
            SHIELD_URL.rstrip("/") + "/v1/shield/tool/check",
            headers={
                "X-API-Key": SHIELD_API_KEY,
                "X-Agent-Key": AGENT_KEY,
                "X-User-Role": USER_ROLE,
            },
            json={"agent_key": AGENT_KEY, "tool_name": name,
                  "tool_params": args, "user_role": USER_ROLE},
        )
        d = r.json()
        reason = ""
        for gr in d.get("guardrail_results", []):
            if not gr.get("passed", True):
                reason = gr.get("message", "")
                break
        return d.get("allowed", True), reason
    except Exception:
        return True, ""


def _build_request(meta, args):
    path = meta["path"]
    query, headers, body = {}, {}, {}
    for k, v in (args or {}).items():
        loc = meta["param_locations"].get(k, "body" if meta["has_body"] else "query")
        if loc == "path":
            path = path.replace("{%s}" % k, str(v))
        elif loc == "query":
            query[k] = v
        elif loc == "header":
            headers[k] = str(v)
        else:
            body[k] = v
    url = BASE_URL.rstrip("/") + "/" + path.lstrip("/")
    json_body = body if (body and meta["method"] not in ("GET", "HEAD")) else None
    return url, query, headers, json_body


@server.call_tool()
async def call_tool(name, arguments):
    meta = _BY_NAME.get(name)
    if not meta:
        return [TextContent(type="text", text="Unknown tool: " + str(name))]

    allowed, reason = await _shield_allows(name, arguments or {})
    if not allowed:
        return [TextContent(type="text", text="Blocked by Shield: " + reason)]

    url, query, headers, json_body = _build_request(meta, arguments or {})
    resp = await _http.request(meta["method"], url,
                               params=query or None, headers=headers or None,
                               json=json_body)
    try:
        payload = resp.json()
        text = json.dumps(payload)
    except Exception:
        text = resp.text
    return [TextContent(type="text", text=text)]


if __name__ == "__main__":
    run_server(server)
'''


def generate_python_server(
    tools: Iterable[ToolSpec],
    *,
    base_url: str,
    title: str = "Generated API",
    server_name: str = "generated-mcp",
    agent_key: str = "generated-agent",
) -> str:
    """Return the source of a standalone Python MCP server for ``tools``."""
    tools_json = json.dumps(_meta(tools))
    return (
        _TEMPLATE
        .replace("@@TITLE@@", title)
        .replace("@@BASE_URL@@", base_url)
        .replace("@@AGENT_KEY@@", agent_key)
        .replace("@@SERVER_NAME@@", server_name)
        # repr() produces a safe single-line Python string literal regardless of
        # quotes/newlines in descriptions — robust embedding of the JSON.
        .replace("@@TOOLS_REPR@@", repr(tools_json))
    )
