"""Idiomatic typed Python MCP server codegen (Speakeasy-style).

Instead of one table-driven dispatcher, this emits:
  - a Pydantic model per operation (typed args, validated on every call)
  - one typed `async def <tool>(args: <Model>)` function per operation
  - a shared `_request()` transport (Shield check → auth → HTTP), so the typed
    functions read like a hand-written SDK
  - retry on 429/5xx with backoff

Depends only on mcp + httpx + pydantic. Reuses the auth plan from
core.openapi.security.
"""

from __future__ import annotations

import json
import re
from typing import Iterable

from core.openapi.tool_mapper import ToolSpec
from core.openapi.codegen.python_gen import _build_auth_fn


def _class_name(tool_name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", tool_name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) + "Args"


def _py_type(schema: dict) -> str:
    t = (schema or {}).get("type")
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"List[{_py_type(schema.get('items') or {})}]"
    if t == "object":
        return "Dict[str, Any]"
    return "Any"


def _ident(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if not s or s[0].isdigit():
        s = "f_" + s
    return s


def _camel(s: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", s)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _unique(name: str, seen: set) -> str:
    candidate, i = name, 2
    while candidate in seen:
        candidate = f"{name}{i}"
        i += 1
    seen.add(candidate)
    return candidate


def _field_type(schema: dict, base: str, prop: str, out: list, seen: set) -> str:
    """Resolve a field's Python type, emitting nested model classes into ``out``."""
    schema = schema or {}
    t = schema.get("type")
    if t == "object" and schema.get("properties"):
        cls = _unique(base + _camel(prop), seen)
        _emit_model(cls, schema, out, seen)
        return cls
    if t == "array":
        inner = _field_type(schema.get("items") or {}, base, prop + "Item", out, seen)
        return f"List[{inner}]"
    return _py_type(schema)


def _emit_model(cls: str, schema: dict, out: list, seen: set) -> None:
    """Emit a Pydantic model class for ``schema`` (nested classes appended first)."""
    props = (schema or {}).get("properties") or {}
    required = set((schema or {}).get("required") or [])
    lines = [f"class {cls}(BaseModel):",
             "    model_config = ConfigDict(populate_by_name=True, extra='ignore')"]
    if not props:
        lines.append("    pass")
    for name, sch in props.items():
        pid = _ident(name)
        # _field_type may append nested classes to `out` before this class is added.
        pytype = _field_type(sch, cls, name, out, seen)
        alias = "" if pid == name else f', alias="{name}"'
        desc = (sch or {}).get("description")
        dkw = f', description={json.dumps(desc)}' if desc else ""
        if name in required:
            default = "..."
        else:
            pytype = f"Optional[{pytype}]"
            default = "None"
        if alias or dkw:
            lines.append(f"    {pid}: {pytype} = Field({default}{alias}{dkw})")
        else:
            lines.append(f"    {pid}: {pytype} = {default}")
    out.append("\n".join(lines))


def _models_for(tool: ToolSpec, seen: set) -> str:
    """Return all model classes for a tool (nested first, arg class last)."""
    out: list = []
    arg_cls = _class_name(tool.name)
    seen.add(arg_cls)
    _emit_model(arg_cls, tool.input_schema or {}, out, seen)
    return "\n\n\n".join(out)


def _fn_src(tool: ToolSpec) -> str:
    cls = _class_name(tool.name)
    meta = {
        "method": tool.method, "path": tool.path,
        "param_locations": tool.param_locations, "has_body": tool.has_body,
        "body_ct": tool.body_content_type,
    }
    # Embed meta as a Python literal via repr() — json.dumps would emit
    # JSON `true/false/null`, which are NameErrors when the function runs.
    return (
        f"async def {_ident(tool.name)}(args: {cls}):\n"
        f"    return await _request({meta!r}, {tool.name!r}, "
        f"args.model_dump(by_alias=True, exclude_none=True))"
    )


def _tools_list_meta(tools: Iterable[ToolSpec]) -> list[dict]:
    return [{"name": t.name, "description": t.description, "inputSchema": t.input_schema}
            for t in tools]


_TEMPLATE = '''"""MCP server for @@TITLE@@ — generated by Votal Shield (typed).

Run:
    pip install mcp httpx pydantic
    API_BASE_URL=@@BASE_URL@@ python server.py

Optional Shield enforcement: set SHIELD_URL, SHIELD_API_KEY, SHIELD_AGENT_KEY, SHIELD_USER_ROLE.
"""

import asyncio
import os
import json
from typing import Any, Dict, List, Optional

import httpx
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

BASE_URL = os.environ.get("API_BASE_URL", "@@BASE_URL@@")
SHIELD_URL = os.environ.get("SHIELD_URL", "")
SHIELD_API_KEY = os.environ.get("SHIELD_API_KEY", "")
AGENT_KEY = os.environ.get("SHIELD_AGENT_KEY", "@@AGENT_KEY@@")
USER_ROLE = os.environ.get("SHIELD_USER_ROLE", "")
MAX_RETRIES = int(os.environ.get("API_MAX_RETRIES", "2"))

server = Server("@@SERVER_NAME@@")
_http = httpx.AsyncClient(timeout=30)

_TOOLS_META = json.loads(@@TOOLS_REPR@@)


@server.list_tools()
async def list_tools():
    return [Tool(name=t["name"], description=t["description"], inputSchema=t["inputSchema"])
            for t in _TOOLS_META]


async def _shield_allows(name, args):
    if not SHIELD_URL:
        return True, ""
    try:
        r = await _http.post(
            SHIELD_URL.rstrip("/") + "/v1/shield/tool/check",
            headers={"X-API-Key": SHIELD_API_KEY, "X-Agent-Key": AGENT_KEY, "X-User-Role": USER_ROLE},
            json={"agent_key": AGENT_KEY, "tool_name": name, "tool_params": args, "user_role": USER_ROLE},
        )
        d = r.json()
        reason = ""
        for gr in d.get("guardrail_results", []):
            if not gr.get("passed", True):
                reason = gr.get("message", ""); break
        return d.get("allowed", True), reason
    except Exception:
        return True, ""


@@AUTH_FN@@


def _build(meta, args):
    path = meta["path"]
    query, headers, body = {}, {}, {}
    for k, v in (args or {}).items():
        loc = meta["param_locations"].get(k, "body" if meta["has_body"] else "query")
        if loc == "path":
            path = path.replace("{%s}" % k, str(v))
        elif loc == "query":
            query[k] = v
        elif loc == "header":
            headers[k] = str(v)
        else:
            body[k] = v
    url = BASE_URL.rstrip("/") + "/" + path.lstrip("/")
    return url, query, headers, body


async def _request(meta, name, args):
    allowed, reason = await _shield_allows(name, args)
    if not allowed:
        raise PermissionError("Blocked by Shield: " + reason)
    url, query, headers, body = _build(meta, args)
    await _apply_auth(headers, query)
    # Encode the body per the operation's declared content type.
    kwargs = {}
    if body and meta["method"] not in ("GET", "HEAD"):
        ct = meta.get("body_ct", "json")
        if ct == "form":
            kwargs["data"] = body
        elif ct == "multipart":
            kwargs["files"] = {k: (None, str(v)) for k, v in body.items()}
        else:
            kwargs["json"] = body
    last = None
    for attempt in range(MAX_RETRIES + 1):
        resp = await _http.request(meta["method"], url, params=query or None,
                                   headers=headers or None, **kwargs)
        if resp.status_code < 500 and resp.status_code != 429:
            try:
                return resp.json()
            except Exception:
                return resp.text
        last = resp
        await asyncio.sleep(0.5 * (2 ** attempt))
    return (last.text if last is not None else "")


@@MODELS@@


@@FUNCTIONS@@

_DISPATCH = {
@@DISPATCH@@
}


@server.call_tool()
async def call_tool(name, arguments):
    entry = _DISPATCH.get(name)
    if not entry:
        return [TextContent(type="text", text="Unknown tool: " + str(name))]
    model_cls, fn = entry
    try:
        model = model_cls(**(arguments or {}))
    except ValidationError as e:
        return [TextContent(type="text", text="Invalid arguments: " + str(e))]
    try:
        result = await fn(model)
    except PermissionError as e:
        return [TextContent(type="text", text=str(e))]
    text = result if isinstance(result, str) else json.dumps(result)
    return [TextContent(type="text", text=text)]


async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
'''


def generate_python_typed_server(
    tools: Iterable[ToolSpec],
    *,
    base_url: str,
    title: str = "Generated API",
    server_name: str = "generated-mcp",
    agent_key: str = "generated-agent",
    security: list | None = None,
) -> str:
    tools = list(tools)
    _seen: set = set()
    models = "\n\n\n".join(_models_for(t, _seen) for t in tools)
    functions = "\n\n\n".join(_fn_src(t) for t in tools)
    dispatch = "\n".join(
        f'    {json.dumps(t.name)}: ({_class_name(t.name)}, {_ident(t.name)}),'
        for t in tools
    )
    tools_json = json.dumps(_tools_list_meta(tools))
    return (
        _TEMPLATE
        .replace("@@TITLE@@", title)
        .replace("@@BASE_URL@@", base_url)
        .replace("@@AGENT_KEY@@", agent_key)
        .replace("@@SERVER_NAME@@", server_name)
        .replace("@@AUTH_FN@@", _build_auth_fn(security or []))
        .replace("@@MODELS@@", models or "# (no models)")
        .replace("@@FUNCTIONS@@", functions or "# (no functions)")
        .replace("@@DISPATCH@@", dispatch)
        .replace("@@TOOLS_REPR@@", repr(tools_json))
    )
