"""Emit a deployable TypeScript MCP server from generated ToolSpecs.

Uses @modelcontextprotocol/sdk and Node's built-in fetch (Node >= 18). Shield
enforcement is baked in and optional at runtime (SHIELD_URL), failing open if
Shield is unreachable. Returns the index.ts source; a matching package.json is
available via generate_package_json().
"""

from __future__ import annotations

import json
from typing import Iterable

from core.openapi.tool_mapper import ToolSpec


def _meta(tools: Iterable[ToolSpec]) -> list[dict]:
    return [{
        "name": t.name,
        "description": t.description,
        "inputSchema": t.input_schema,
        "method": t.method,
        "path": t.path,
        "param_locations": t.param_locations,
        "has_body": t.has_body,
    } for t in tools]


_TEMPLATE = '''// MCP server for @@TITLE@@ — generated by Votal Shield.
// Run: npm install && API_BASE_URL=@@BASE_URL@@ node dist/index.js
// Optional Shield enforcement: set SHIELD_URL, SHIELD_API_KEY, SHIELD_AGENT_KEY, SHIELD_USER_ROLE
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const BASE_URL = process.env.API_BASE_URL || "@@BASE_URL@@";
const SHIELD_URL = process.env.SHIELD_URL || "";
const SHIELD_API_KEY = process.env.SHIELD_API_KEY || "";
const AGENT_KEY = process.env.SHIELD_AGENT_KEY || "@@AGENT_KEY@@";
const USER_ROLE = process.env.SHIELD_USER_ROLE || "";

const TOOLS: any[] = @@TOOLS_JSON@@;
const BY_NAME: Record<string, any> = Object.fromEntries(TOOLS.map((t) => [t.name, t]));

const server = new Server(
  { name: "@@SERVER_NAME@@", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS.map((t) => ({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  })),
}));

async function shieldAllows(name: string, args: any): Promise<[boolean, string]> {
  if (!SHIELD_URL) return [true, ""];
  try {
    const r = await fetch(SHIELD_URL.replace(/\\/$/, "") + "/v1/shield/tool/check", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": SHIELD_API_KEY,
        "X-Agent-Key": AGENT_KEY,
        "X-User-Role": USER_ROLE,
      },
      body: JSON.stringify({
        agent_key: AGENT_KEY, tool_name: name, tool_params: args, user_role: USER_ROLE,
      }),
    });
    const d: any = await r.json();
    let reason = "";
    for (const gr of d.guardrail_results || []) {
      if (gr.passed === false) { reason = gr.message || ""; break; }
    }
    return [d.allowed !== false, reason];
  } catch {
    return [true, ""];
  }
}

function buildRequest(meta: any, args: any) {
  let path: string = meta.path;
  const query: Record<string, any> = {};
  const headers: Record<string, string> = {};
  const body: Record<string, any> = {};
  for (const [k, v] of Object.entries(args || {})) {
    const loc = meta.param_locations[k] || (meta.has_body ? "body" : "query");
    if (loc === "path") path = path.replace("{" + k + "}", String(v));
    else if (loc === "query") query[k] = v;
    else if (loc === "header") headers[k] = String(v);
    else body[k] = v;
  }
  const qs = new URLSearchParams(query as any).toString();
  const url = BASE_URL.replace(/\\/$/, "") + "/" + path.replace(/^\\//, "") + (qs ? "?" + qs : "");
  const jsonBody =
    Object.keys(body).length && meta.method !== "GET" && meta.method !== "HEAD"
      ? JSON.stringify(body)
      : undefined;
  return { url, headers, jsonBody };
}

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const name = req.params.name;
  const args = req.params.arguments || {};
  const meta = BY_NAME[name];
  if (!meta) return { content: [{ type: "text", text: "Unknown tool: " + name }] };

  const [ok, reason] = await shieldAllows(name, args);
  if (!ok) return { content: [{ type: "text", text: "Blocked by Shield: " + reason }] };

  const { url, headers, jsonBody } = buildRequest(meta, args);
  const resp = await fetch(url, {
    method: meta.method,
    headers: { "Content-Type": "application/json", ...headers },
    body: jsonBody,
  });
  const text = await resp.text();
  return { content: [{ type: "text", text }] };
});

const transport = new StdioServerTransport();
await server.connect(transport);
'''

_PACKAGE_JSON = {
    "name": "@@SERVER_NAME@@",
    "version": "1.0.0",
    "type": "module",
    "bin": {"@@SERVER_NAME@@": "dist/index.js"},
    "scripts": {"build": "tsc"},
    "dependencies": {"@modelcontextprotocol/sdk": "^1.0.0"},
    "devDependencies": {"typescript": "^5.4.0", "@types/node": "^20.0.0"},
}


def generate_typescript_server(
    tools: Iterable[ToolSpec],
    *,
    base_url: str,
    title: str = "Generated API",
    server_name: str = "generated-mcp",
    agent_key: str = "generated-agent",
) -> str:
    """Return the index.ts source of a standalone TypeScript MCP server."""
    tools_json = json.dumps(_meta(tools), indent=2)
    return (
        _TEMPLATE
        .replace("@@TITLE@@", title)
        .replace("@@BASE_URL@@", base_url)
        .replace("@@AGENT_KEY@@", agent_key)
        .replace("@@SERVER_NAME@@", server_name)
        .replace("@@TOOLS_JSON@@", tools_json)  # JSON is a valid JS literal
    )


def generate_package_json(server_name: str = "generated-mcp") -> str:
    return json.dumps(_PACKAGE_JSON, indent=2).replace("@@SERVER_NAME@@", server_name)
