"""PAC file generation.

Task 5 of docs/spec-swg-icap-adapter.md.

The PAC is the privacy control, not just a routing config. Traffic it sends
`DIRECT` never reaches the proxy, is never decrypted, and cannot be inspected
even by accident. That is the sentence a works council reads, so bypass is
evaluated before inspection and the generated file says so in a comment the
operator can point at.

The missing `; DIRECT` fallback on the inspect branch is deliberate and is the
same knob as `SHIELD_ICAP_FAIL_OPEN` and Squid's `bypass=`, expressed a third
way: with no fallback, killing the proxy breaks AI access rather than silently
bypassing inspection.
"""
from __future__ import annotations

from icap.config import IcapConfig



def _match_expr(hosts: tuple[str, ...] | list[str], indent: str = "      ") -> str:
    """A JS boolean over the host list.

    Each entry matches the domain itself and its subdomains, never a suffix
    collision: "chase.com" must not be satisfied by "notchase.com".
    """
    if not hosts:
        return indent + "false"
    terms = []
    for h in hosts:
        h = h.lower()
        terms.append(f'shExpMatch(host, "{h}") || shExpMatch(host, "*.{h}")')
    return " ||\n".join(indent + t for t in terms)


def render_pac(cfg: IcapConfig) -> str:
    """Render the tenant's PAC file."""
    fallback = "; DIRECT" if cfg.mode != "enforce" else ""
    fallback_note = (
        "monitor mode: if the proxy is down, browsing continues uninspected."
        if fallback
        else "enforce mode: no DIRECT fallback, so killing the proxy blocks AI access."
    )
    return f"""// Generated by shield-icap. Do not edit by hand.
// Policy version: {cfg.version}   Mode: {cfg.mode}
//
// Hosts returned DIRECT below are never sent to the proxy, are never
// decrypted, and cannot be inspected. Bypass is checked FIRST, on purpose.
function FindProxyForURL(url, host) {{
  host = host.toLowerCase();

  // 1. Never inspected.
  if (
{_match_expr(tuple(cfg.bypass_hosts))}
  ) {{
    return "DIRECT";
  }}

  // 2. Inspected: the AI surface.
  // {fallback_note}
  if (
{_match_expr(tuple(cfg.ai_hosts))}
  ) {{
    return "PROXY {cfg.pac_proxy}{fallback}";
  }}

  // 3. Everything else goes straight out.
  return "DIRECT";
}}
"""
