name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USER: sundi133

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/llm-shield:v2
            ${{ env.DOCKERHUB_USER }}/llm-shield:latest
            ${{ env.DOCKERHUB_USER }}/llm-shield:${{ github.sha }}
